[auth]
# these fields are MANDATORY
username="username"
password="password"

[insta]
# replace this list with the users you wish to target
insta_user_list = [
"user1",
"user2",
"user3",
]

[file]
output_location="output"
